#!/usr/bin/env bash
# car2x-06-gps-setup.sh
# phase 6: gpsd + chrony + device check
# safe to re-run

set -euo pipefail

# shared helpers + env
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "${SCRIPT_DIR}/car2x-99-utilities.sh" ]]; then
    echo "ERROR: car2x-99-utilities.sh not found in $SCRIPT_DIR"
    exit 1
fi
source "${SCRIPT_DIR}/car2x-99-utilities.sh"

# env config
if [[ -f /etc/car2x/environment ]]; then
    source /etc/car2x/environment
elif [[ -f "${SCRIPT_DIR}/environment" ]]; then
    source "${SCRIPT_DIR}/environment"
fi

# config (with sane defaults)
GPS_DEV="${CAR2X_USB_GPS:-/dev/car2x-gps}"
GPS_BAUDRATE="${CAR2X_GPS_BAUDRATE:-115200}"
ENABLE_GPS="${CAR2X_ENABLE_GPS:-1}"
ENABLE_CHRONY="${CAR2X_GPS_CHRONY_ENABLE:-1}"
CHRONY_OFFSET="${CAR2X_GPS_CHRONY_OFFSET:-0.0}"
CHRONY_DELAY="${CAR2X_GPS_CHRONY_DELAY:-0.2}"
CHRONY_CONF="/etc/chrony/chrony.conf"

# entry

log_info "----------------------------------------------------"
log_info " Phase 6: GPS setup (gpsd + Chrony NTP)"
log_info "----------------------------------------------------"
log_info ""

# is gps enabled at all
if [[ "$ENABLE_GPS" != "1" ]]; then
    log_warn "GPS service disabled (CAR2X_ENABLE_GPS=$ENABLE_GPS)"
    log_warn "Skipping GPS setup phase"
    exit 0
fi

# need root
if ! check_root; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

log_info "Step 1: installing GPS dependencies"

install_gps_packages() {
    local packages_to_install=()

    # check each package on its own
    if ! command -v gpspipe &>/dev/null; then
        packages_to_install+=("gpsd" "gpsd-clients")
    fi

    if ! command -v jq &>/dev/null; then
        packages_to_install+=("jq")
    fi

    if [[ "$ENABLE_CHRONY" == "1" ]] && ! command -v chronyc &>/dev/null; then
        packages_to_install+=("chrony")
    fi

    if [[ ${#packages_to_install[@]} -eq 0 ]]; then
        log_success "All GPS packages already installed"
        return 0
    fi

    log_info "Installing packages: ${packages_to_install[*]}"

    if command -v apt &>/dev/null; then
        apt update -qq || log_warn "apt update had warnings"
        apt install -y "${packages_to_install[@]}" || {
            log_error "Failed to install GPS packages"
            return 1
        }
    elif command -v dnf &>/dev/null; then
        dnf install -y "${packages_to_install[@]}" || {
            log_error "Failed to install GPS packages via dnf"
            return 1
        }
    else
        log_error "Unsupported package manager. Install gpsd, gpsd-clients, jq, chrony manually."
        return 1
    fi

    log_success "GPS packages installed succesfully"
}

if ! install_gps_packages; then
    exit 1
fi

log_info ""
log_info "Step 2: validating GPS device symlink"

# udev needs a moment after phase 5
max_tries=10
tries=0

while [[ ! -e "$GPS_DEV" ]] && [[ $tries -lt $max_tries ]]; do
    log_warn "GPS device symlink not found: $GPS_DEV (waiting...)"
    sleep 1
    ((tries++))
    udevadm trigger --subsystem-match=tty || true
done

if [[ ! -e "$GPS_DEV" ]]; then
    log_error "GPS device symlink not found: $GPS_DEV"
    log_error "Make sure phase 5 (USB setup) created the udev rules"
    log_error "Check: ls -la /dev/car2x-*"
    exit 1
fi

if [[ ! -c "$GPS_DEV" ]]; then
    log_error "GPS device exists but is not a character device: $GPS_DEV"
    exit 1
fi

log_success "GPS device validated: $GPS_DEV"

log_info ""
log_info "Step 3: configuring gpsd (custom car2x service)"

log_info "Disabling standard gpsd (avoids socket-activation conflicts)..."

systemctl stop gpsd.service 2>/dev/null || true
systemctl stop gpsd.socket 2>/dev/null || true
systemctl stop car2x-gpsd.service 2>/dev/null || true

pkill -9 gpsd 2>/dev/null || true
sleep 1

systemctl mask gpsd.service 2>/dev/null || true
systemctl mask gpsd.socket 2>/dev/null || true
log_success "Standard gpsd.service and gpsd.socket masked"

OD="/etc/systemd/system/gpsd.service.d"
if [[ -d "$OD" ]]; then
    rm -rf "$OD"
    log_debug "Old override directory removed"
fi

CAR2X_GPSD_SERVICE="/etc/systemd/system/car2x-gpsd.service"

log_info "Creating the Car2X gpsd service..."

cat > "$CAR2X_GPSD_SERVICE" <<EOF
# Car2X GPS Daemon Service
# Generated by car2x-06-gps-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This replaces the standard gpsd service to avoid socket-activation conflicts

[Unit]
Description=Car2X GPS Daemon (gpsd)
After=local-fs.target network.target
Wants=local-fs.target
ConditionPathExists=$GPS_DEV

[Service]
Type=simple
ExecStart=/usr/sbin/gpsd -N -n -F /var/run/gpsd.sock $GPS_DEV
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

log_success "car2x-gpsd.service written"

systemctl daemon-reload
systemctl enable --now car2x-gpsd.service

log_info "Starting car2x-gpsd.service..."

sleep 3

if systemctl is-active car2x-gpsd.service &>/dev/null; then
    log_success "car2x-gpsd.service is active"
else
    log_error "car2x-gpsd.service failed to start"
    log_error "Check logs: journalctl -u car2x-gpsd.service -n 50"
    exit 1
fi


if [[ "$ENABLE_CHRONY" == "1" ]]; then
    log_info ""
    log_info "Step 4: checking gpsd SHM interface"

    # gpsd only creates SHM once it has a time fix, so missing is not fatal
    if [[ -e /dev/shm/gpsd_shm_0 ]]; then
        log_success "gpsd SHM interface available: /dev/shm/gpsd_shm_0"
    else
        log_warn "gpsd SHM interface not available (no GPS fix yet)"
        log_warn "This is normal for indoor tests without sky view"
        log_warn "SHM appears automatically once GPS has a fix"
        log_warn "Chrony will then pick up GPS time on its own"
    fi
fi


if [[ "$ENABLE_CHRONY" == "1" ]]; then
    log_info ""
    log_info "Step 5: configuring chrony NTP server"

    if [[ ! -f "$CHRONY_CONF" ]]; then
        log_error "Chrony configuration not found: $CHRONY_CONF"
        exit 1
    fi

    if grep -q "^refclock SHM 0" "$CHRONY_CONF" 2>/dev/null; then
        log_success "Chrony GPS refclock already configured"
    else
        log_info "Adding GPS reference clock to Chrony..."

        backup_file "$CHRONY_CONF"

        cat >> "$CHRONY_CONF" <<EOF

# Car2X GPS Time Synchronization - Added by car2x-06-gps-setup.sh
# Modified: $(date -u +%Y-%m-%dT%H:%M:%SZ)

# GPS reference clock via gpsd SHM interface
refclock SHM 0 offset $CHRONY_OFFSET delay $CHRONY_DELAY refid GPS precision 1e-1

# Allow local network time synchronization (optional)
# allow 192.168.0.0/16
EOF

        log_success "GPS refclock added to Chrony configuration"
    fi

    log_info "Restarting Chrony service..."
    systemctl restart chrony.service || {
        log_error "Failed to restart chrony.service"
        exit 1
    }

    sleep 2

    if systemctl is-active chrony.service &>/dev/null; then
        log_success "Chrony service is active"

        log_info "Chrony time sources:"
        chronyc sources || log_warn "Could not query chrony sources"
    else
        log_error "Chrony service failed to start"
        log_error "Check logs: journalctl -u chrony.service -n 50"
        exit 1
    fi
else
    log_warn "Chrony NTP disabled (CAR2X_GPS_CHRONY_ENABLE=$ENABLE_CHRONY)"
    log_warn "Skipping Chrony configuration"
fi


log_info ""
log_info "Step 6: final GPS setup validation"

log_info "Testing GPS data stream (5 second timeout)..."
if timeout 5 gpspipe -w -n 3 "$GPS_DEV" 2>/dev/null | grep -q '"class":"TPV"'; then
    log_success "GPS data stream validated (TPV messages received)"
else
    log_warn "GPS data validation timed out (device may need GPS fix)"
    log_warn "This is normal indoors or without clear sky view"
fi

if id car2x &>/dev/null; then
    if groups car2x | grep -q dialout; then
        log_success "car2x user has dialout group access"
    else
        log_warn "Adding car2x user to dialout group..."
        usermod -a -G dialout car2x || log_error "Failed to add car2x to dialout"
    fi
fi


log_info ""
log_success "----------------------------------------------------"
log_success " Phase 6: GPS setup done"
log_success "----------------------------------------------------"
log_success ""
log_success "GPS configuration summary:"
log_success "  Device:        $GPS_DEV"
log_success "  Baudrate:      $GPS_BAUDRATE"
log_success "  gpsd:          car2x-gpsd.service (custom service)"
if [[ "$ENABLE_CHRONY" == "1" ]]; then
    log_success "  Chrony NTP:    active (GPS refclock configured)"
else
    log_success "  Chrony NTP:    disabled"
fi
log_success ""
log_success "Verification commands:"
log_success "  Test GPS:      gpspipe -w -n 10"
log_success "  GPS status:    gpsmon"
log_success "  Chrony status: chronyc sources"
log_success "  gpsd log:      journalctl -u car2x-gpsd.service -n 50"
log_success ""

exit 0
